version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER:-root}
      - DB_PASS=${DB_PASS:-}
      - DB_NAME=${DB_NAME:-barcie_db}
    depends_on:
      - db

  db:
    image: mariadb:10.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS:-}
      MYSQL_DATABASE: ${DB_NAME:-barcie_db}
      MYSQL_USER: ${DB_USER:-root}
      MYSQL_PASSWORD: ${DB_PASS:-}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
