name: Build and Publish Test to Docker Hub
permissions:
  contents: read

on:
  push:
    branches: ["test"]
  pull_request:
    branches: ["test"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag carlxd0711/barcie:test
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: "carlxd0711"
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push the Docker image
        run: docker push carlxd0711/barcie:test
